### ISSUE TITLE
failed to install on osx 10.9.3

### ISSUE THREAD

**Issue by sleetdrop** [codeaholics/node-rdb-tools#4]
npm install rdb-tools
|

> int64-native@0.2.1 install /Users/jiangyuan/Documents/learn/node/rdb/node_modules/rdb-tools/node_modules/int64-native
> node-gyp configure && node-gyp build

  CXX(target) Release/obj.target/Int64/src/main.o
  CXX(target) Release/obj.target/Int64/src/Int64.o
  SOLINK_MODULE(target) Release/Int64.node
  SOLINK_MODULE(target) Release/Int64.node: Finished

> lzf@0.1.3 install /Users/jiangyuan/Documents/learn/node/rdb/node_modules/rdb-tools/node_modules/lzf
> node-gyp rebuild

  CXX(target) Release/obj.target/lzf/src/lzf.o
  CXX(target) Release/obj.target/lzf/src/lzf/lzf_c.o
  CXX(target) Release/obj.target/lzf/src/lzf/lzf_d.o
  SOLINK_MODULE(target) Release/lzf.node
  SOLINK_MODULE(target) Release/lzf.node: Finished

> rdb-tools@0.1.0 install /Users/jiangyuan/Documents/learn/node/rdb/node_modules/rdb-tools
> node-gyp configure build

  CC(target) Release/obj.target/Crc64/src/crc64.o
  CXX(target) Release/obj.target/Crc64/src/Crc64.o
  SOLINK_MODULE(target) Release/Crc64.node
duplicate symbol __ZN5Crc644InitEN2v86HandleINS0_6ObjectEEE in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc643NewERKN2v89ArgumentsE in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc644PushERKN2v89ArgumentsE in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc648GetValueERKN2v89ArgumentsE in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZTV5Crc64 in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc64C1Ev in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc64C2Ev in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc64D0Ev in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc64D1Ev in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol __ZN5Crc64D2Ev in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol _init in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
duplicate symbol _Crc64_module in:
    Release/obj.target/Crc64/src/crc64.o
    Release/obj.target/Crc64/src/Crc64.o
ld: 12 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: **\* [Release/Crc64.node] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:807:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /Users/jiangyuan/Documents/learn/node/rdb/node_modules/rdb-tools
gyp ERR! node -v v0.10.28
gyp ERR! node-gyp -v v0.13.1
gyp ERR! not ok
npm ERR! rdb-tools@0.1.0 install: `node-gyp configure build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the rdb-tools@0.1.0 install script.
npm ERR! This is most likely a problem with the rdb-tools package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure build
npm ERR! You can get their info via:
npm ERR!     npm owner ls rdb-tools
npm ERR! There is likely additional logging output above.

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "rdb-tools"
npm ERR! cwd /Users/jiangyuan/Documents/learn/node/rdb
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.16
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /Users/jiangyuan/Documents/learn/node/rdb/npm-debug.log
npm ERR! not ok code 0

clang version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)

I have tried g++-4.8, also failed with the same reason.

**Comment by codeaholics** [comment]
I can't test this because I don't have a Mac. However, I'm pretty sure this is the same issue that I merged a PR for a few days back. Could you try with the head of master, please?

**Comment by sleetdrop** [comment]
npm install git+https://github.com/codeaholics/node-rdb-tools.git
just works

thanks a lot.

**Comment by codeaholics** [comment]
No worries. I'll publish an official release soon. Hopefully today.

**Comment by codeaholics** [comment]
v0.1.1 published to npm with this fix. Sometimes it can take a few hours for things to appear on npm.
